#!/bin/bash

IMAGE_TAG=chem279/final
MOUNT_DIR=$(dirname $1)
INPUT="${1%.*}.mop"

#echo "MNDO NOOPT XYZ NOREOR MULLIK LARGE 1ELECTRON ALLVEC DENSITY FOCK HCORE DFORCE LET" > $INPUT
#echo "MNDO XYZ NOREOR GRADIENTS MULLIK LARGE 1ELECTRON ALLVEC DENSITY FOCK HCORE LET" > $INPUT
echo "MNDO XYZ CYCLES=1 GNORM=100.0 ENPART NOREOR GRADIENTS MULLIK LARGE 1ELECTRON ALLVEC DENSITY FOCK HCORE LET" > $INPUT
#echo "MNDO PRECISE XYZ ENPART NOREOR GRADIENTS MULLIK LARGE 1ELECTRON ALLVEC DENSITY FOCK HCORE LET" > $INPUT
echo " " >> $INPUT
echo " " >> $INPUT
tail -n +3 $1 >> $INPUT

# Run calculation
docker run --rm -v $MOUNT_DIR:/workdir $IMAGE_TAG $INPUT
